# Main Application Configuration
spring:
  application:
    name: Smoking Cessation Platform

  profiles:
    active: dev

  # Default JPA Settings
  jpa:
    open-in-view: false
    show-sql: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Application Configuration
app:
  version: 1.0.0